# Full Concept of Numpy in Python

# Chapter no 1 

In [1]:
# Numpy stands for Numerical python 

In [6]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [7]:
# python list

In [3]:
python_list = [1,2,3,4,5,6]
print(python_list)


[1, 2, 3, 4, 5, 6]


In [4]:
# Numpy array
import numpy as np
numpy_array = np.array([1,2,3,4,5,6,7])
# numpy_array
print(numpy_array)

[1 2 3 4 5 6 7]


# Array

In [5]:
# array of collection of number 
# array of value 
marks1 = 12
marks2 = 19
marks3 = 19

marks_of_class = [12,19,18] #this is array in structure way


# 1D Array

In [6]:
# one dimensional array
# lists of number such as vector v = [23,34,34,] or v = c(23,34,34,)
# store in row
# e.g --> vector 

import numpy as np
one_d_array = np.array([12,23,34,45])
print(one_d_array)

[12 23 34 45]


# 2D Array 

In [7]:
# such like table or matrix 
# e.g ----> excel and csv file 

import numpy as np 
two_d_array = np.array([[12,34,54]
                       ,[34,23,12]])
print(two_d_array)



[[12 34 54]
 [34 23 12]]


In [8]:
import numpy as np 
two_d_array = np.array(([12,34,54],
                        [34,23,12],
                        [2,4,5]))
# print(two_d_array)
print(two_d_array.ndim)

2


# Multiple Dimensional Array 

In [9]:
# stored data at multiple level 
# multiple layer of data
import numpy as np 
multi_d_array = np.array([[[1,2,3],[4,5,6]], [[7,8,9],[2,3,4]]])
print(multi_d_array.ndim)
print(multi_d_array)


3
[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [2 3 4]]]


# Creating array from python list 

In [10]:
import numpy as np 
arrays = np.array([1,3,4,5,6,4,3,5])
print(arrays)

[1 3 4 5 6 4 3 5]


# With Default Value 

In [11]:
import numpy as np 
zeros = np.zeros(10)
print(zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [12]:
import numpy as np 
ones = np.ones((3,4))  # rows and columns 
print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [13]:
import numpy as np 
ones = np.ones([5,5])
print(ones)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


# Give Specific Value used full() function

In [14]:
import numpy as np 
fill = np.full([3,4],9) # shape and fill value such 9 and so on 
fill

array([[9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9]])

# Creating Sequences of Number in Numpy

In [15]:
# arange(start , stop,step) function 
import numpy as np
number = np.arange(0,20,2)
print(number)

[ 0  2  4  6  8 10 12 14 16 18]


In [16]:
nu = np.arange(10,101) # make a number of sequnece of series of any number than we use the arange function
nu   

array([ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,
        23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,
        36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,
        49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,
        62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,
        75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,
        88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

# Creating identity Matrixes 

In [17]:
# eye(size)
import numpy as np
identity_matix = np.eye(4)
print(identity_matix) 

# one on the diagonal with zeros else where 

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# CHAPTER -2
# Array Properties & Operations

In [18]:
 # array (shape ,size,type of data means dtype ,ndim ---> dimension of array)


# Shape

In [19]:
# it give the shape in form of number ---- >(rows,columns)

import numpy as np
arry_2d = np.array([[1,2,5,3,],
                    [45,53,33,6]])
print(arry_2d)


[[ 1  2  5  3]
 [45 53 33  6]]


In [20]:
print(arry_2d.shape)  # 2 rows and 4 columns 

(2, 4)


# Size 

In [21]:
# its give me the size of element in the list of array 
print(arry_2d.size)

8


# ndim function


In [22]:
print(arry_2d.ndim)

2


In [23]:
import numpy as np

three_d_array = np.array([
    [[1, 2, 3], [4, 5, 6]],      # 1st 2D matrix
    [[7, 8, 9], [10, 11, 12]],   # 2nd 2D matrix
    [[13, 14, 15], [16, 17, 18]] # 3rd 2D matrix
])

print("3D Array:\n", three_d_array)
print("Shape:", three_d_array.shape)


3D Array:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
Shape: (3, 2, 3)


In [24]:
three_d_array.ndim

3

In [25]:
import numpy as np

# 1D Array
one_d_array = np.array([1, 2, 3, 4, 5])

# 2D Array (Matrix)
two_d_array = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

# 3D Array
three_d_array = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])

# Print all arrays and their shapes
print("1D Array:\n", one_d_array)
print("Shape:", one_d_array.shape)

print("\n2D Array:\n", two_d_array)
print("Shape:", two_d_array.shape)

print("\n3D Array:\n", three_d_array)
print("Shape:", three_d_array.shape)


1D Array:
 [1 2 3 4 5]
Shape: (5,)

2D Array:
 [[10 20 30]
 [40 50 60]]
Shape: (2, 3)

3D Array:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Shape: (2, 2, 3)


In [26]:
# Dimemsion of Array make 

import pandas as pd 

array_1d = np.array([1,2,3,4])
array_2d = np.array([[1,2],[3,4]])
array_3d = np.array([[[1,2,3]],
                     [[4,5,6]],
                     [[7,8,9]]])
print(array_1d,"\n")
print(array_2d,"\n")
print(array_3d)
print('--------shape ------------')
print(array_1d.shape)
print(array_2d.shape)
print(array_3d.shape)
print("------------------ ndim ------------")
print(array_1d.ndim)
print(array_2d.ndim)
print(array_3d.ndim)

[1 2 3 4] 

[[1 2]
 [3 4]] 

[[[1 2 3]]

 [[4 5 6]]

 [[7 8 9]]]
--------shape ------------
(4,)
(2, 2)
(3, 1, 3)
------------------ ndim ------------
1
2
3


In [27]:
array_3d = np.array([
    [[1,2,3],[23,34,23]],
    [[4,5,6],[23,34,23]],
    [[4,5,6],[23,34,23]]
                    ])
print(array_3d.shape)
# 3 "matrices"

# Each matrix has 2 rows

# Each row has 3 elements

(3, 2, 3)


In [28]:
array_3d = np.array([
    [[1,2,3], [4,5,6]],
    [[7,8,9], [10,11,12]]
])
print(array_3d.shape)


(2, 2, 3)


# dtype is datatypes of element 

In [29]:
array_3d = np.array([
    [[1,2,3], [4,5,6]],
    [[7,8,9], [10,11,12]]
])
print(array_3d.dtype)
# it give the datatype of data 


int32


In [30]:
import numpy as np

# 1D array of strings
fruits = np.array(['apple', 'banana', 'cherry', 'date'])

print("Array of Strings:", fruits)
print("Shape:", fruits.shape)
print("Data Type:", fruits.dtype)


Array of Strings: ['apple' 'banana' 'cherry' 'date']
Shape: (4,)
Data Type: <U6


# Change any datatype into another than we use as.type() function

In [37]:
# conversion of any data into another datatype 
# hiring the type conversion
import numpy as np
arr = np.array([1.2,3.5,4.5,6.7],dtype=int)
arr

array([1, 3, 4, 6])

In [38]:
int_arr = arr.astype(int)
print(int_arr)
print(int_arr.dtype)
type(int_arr)

[1 3 4 6]
int32


numpy.ndarray

In [39]:
import numpy as np

arr_int = np.array([1, 2, 3, 4])
arr_float = arr_int.astype(float)

print("Original:", arr_int, arr_int.dtype)
print("Converted:", arr_float, arr_float.dtype)


Original: [1 2 3 4] int32
Converted: [1. 2. 3. 4.] float64


In [40]:
arr_bool = np.array([True, False, True])
arr_int = arr_bool.astype(int)

print("Converted to int:", arr_int)


Converted to int: [1 0 1]


# Math Operator using Numpy arrays 

In [41]:
import numpy as np

arr_int = np.array([1, 2, 3, 4])

print(arr_int + 10)
print(arr_int - 10)
print(arr_int * 10)
print(arr_int / 10)
print(arr_int % 10)
print(arr_int // 10)
print(arr_int ** 10)

# we can easy operation perfrom with the arrays on simple syntax not use for loop each time  

[11 12 13 14]
[-9 -8 -7 -6]
[10 20 30 40]
[0.1 0.2 0.3 0.4]
[1 2 3 4]
[0 0 0 0]
[      1    1024   59049 1048576]


# Aggregation Function in Numpy


In [42]:
# summary of using number no 
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print("Sum:", np.sum(arr))             # 15
print("Mean:", np.mean(arr))           # 3.0
print("Median:", np.median(arr))       # 3.0
print("Standard Deviation:", np.std(arr))  # 1.414...
print("Minimum:", np.min(arr))         # 1
print("Maximum:", np.max(arr))         # 5
print("variance:", np.var(arr))         


Sum: 15
Mean: 3.0
Median: 3.0
Standard Deviation: 1.4142135623730951
Minimum: 1
Maximum: 5
variance: 2.0


In [43]:
matrix = np.array([[1, 2], [3, 4]])

print(np.sum(matrix, axis=0))  # [4, 6] (column-wise sum)
print(np.sum(matrix, axis=1))  # [3, 7] (row-wise sum)


[4 6]
[3 7]


# CHAPTER - 3
# Indexing & Slicing

In [44]:
# indexing  pick the specific index 
# slicing   pick multiple element [start:stop:step]
# fancy indexing 
# Boolean masking 



# Indexing 

In [45]:
import numpy as np

arr = np.array([10,9,3,4,15])
print(arr[3])

4


In [46]:
print(arr[1])

9


In [47]:
# array[index]  -- 1D array 
# array[row,col]  -- 2D array 

In [48]:
print(arr[-1])  #also negative index

15


# SLicing (Extracting the subsets of data )

In [49]:
# slicing   pick multiple element [start:stop:step]
import numpy as np

arr = np.array([10,9,3,4,15,34,45,45,56,67,89])
print(arr[0:2])
print(arr[0:9:2])
print(arr[:7])
print(arr[::2])
print(arr[::-1])


[10  9]
[10  3 15 45 56]
[10  9  3  4 15 34 45]
[10  3 15 45 56 89]
[89 67 56 45 45 34 15  4  3  9 10]


# fanncy Indexing 

In [50]:
# selecting the multiple element at once
import numpy as np

arr = np.array([10,9,3,4,15,34,45,45,56,67,8])
print(arr[[2,4,6]])

[ 3 15 45]


# Fliter / Boolean masking 

In [51]:
# filter data based on conditions 

In [52]:
import numpy as np

arr = np.array([10,9,3,4,15,34,45,45,56,67,8])
print(arr[arr > 25])
print([arr > 25])
print(arr[arr < 25])

[34 45 45 56 67]
[array([False, False, False, False, False,  True,  True,  True,  True,
        True, False])]
[10  9  3  4 15  8]


# Reshaping and Manipulating Arrays

In [53]:
# reshape(row,col)
import numpy as np

arr = np.array([10,9,3,4,15,34,45,45,56,67])
print(arr.reshape(5,2))

[[10  9]
 [ 3  4]
 [15 34]
 [45 45]
 [56 67]]


# flatten 

In [54]:
# .reval --- view original array effect 
# flatten -- return a copy  original array not effect 
# flatten and reval the change the ARRAY into 1D

import numpy as np
arr = np.array([[2,4],[3,4]])
arr
print(arr.ravel())
print(arr.flatten())
# it give the result same but 

[2 4 3 4]
[2 4 3 4]


In [55]:
# ------------- Summary of chapter ---------------
# indexing
# siIving
# fancy indexing
# boolean masking
# array shape
# ravel, flatten

# CHAPTER - 4
# Reshaping & Manipulating Arrays

In [56]:
# now we deep into the advanced part of Numpy

# Advance Numpy

# Insert element in array in Numpy

In [57]:
import numpy as np

arr = np.array([10,9,3,4,15,34,45,45,56,67])
# np.array(arr_list , index , value ,axis = None)
arr1 = np.insert(arr,1,99,axis = 0)    # axis is 0 for row and 1 column
arr1

array([10, 99,  9,  3,  4, 15, 34, 45, 45, 56, 67])

In [58]:
import numpy as np
arr_2d = np.array([[1, 2], [2, 3]])
print(arr_2d)
print("before")
import numpy as np

# Creating a 2D array directly
arr_2d = np.array([[1, 2], [2, 3]])
new_arr = np.insert(arr_2d,0,[4,5],axis = 1)
# Print the array and its number of dimensions
print(new_arr)
print("Number of dimensions:", arr_2d.ndim)
print("after")


[[1 2]
 [2 3]]
before
[[4 1 2]
 [5 2 3]]
Number of dimensions: 2
after


In [59]:
import numpy as np
arr_2d = np.array([[1, 2], [2, 3]])
print(arr_2d)
print("before")
import numpy as np

# Creating a 2D array directly
arr_2d = np.array([[1, 2], [2, 3]])
new_arr = np.insert(arr_2d,0,[4,5],axis = 0)
# Print the array and its number of dimensions
print(new_arr)
print("Number of dimensions:", arr_2d.ndim)
print("after")

[[1 2]
 [2 3]]
before
[[4 5]
 [1 2]
 [2 3]]
Number of dimensions: 2
after


In [60]:
import numpy as np
arr_2d = np.array([[1, 2], [2, 3]])
print(arr_2d)
print("before")
import numpy as np

# Creating a 2D array directly
arr_2d = np.array([[1, 2], [2, 3]])
new_arr = np.insert(arr_2d,0,[4,5],axis = None) # print flatten 
# Print the array and its number of dimensions
print(new_arr)
print("Number of dimensions:", arr_2d.ndim)
print("after")

[[1 2]
 [2 3]]
before
[4 5 1 2 2 3]
Number of dimensions: 2
after


# Append() 

In [36]:
# any element add in the array at last postion then we used append  

In [61]:
arr_2d = np.array([[1, 2], [2, 3]])
new_arr = np.append(arr_2d,[4,5,3,45,66,45,]) # print flatten 
print(new_arr)

[ 1  2  2  3  4  5  3 45 66 45]


# Concatenation in Numpy

In [67]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = np.concatenate((a, b))
print(result)
# for 1D array 


[1 2 3 4 5 6]


In [68]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

result = np.concatenate((a, b), axis=0)
print(result)


[[1 2]
 [3 4]
 [5 6]]


In [69]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

result = np.concatenate((a, b), axis=1)
print(result)


[[1 2 5 6]
 [3 4 7 8]]


# Delete Function ()

In [70]:
import numpy as np

a = np.array([10, 20, 30, 40, 50])
result = np.delete(a, 2)  # Deletes the element at index 2 (30)
print(result)


[10 20 40 50]


In [72]:
b = np.array([[1, 2, 3], [4, 5, 6]])
result2 = np.delete(b, 1, axis=1)  # Deletes the 2nd row of column
print(result2)


[[1 3]
 [4 6]]


# Sacking Array

In [73]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = np.stack((a, b))  # Default axis=0
print(result)
# Output:
# [[1 2 3]
#  [4 5 6]]


[[1 2 3]
 [4 5 6]]


In [78]:
result = np.stack((a, b), axis=1) # and also if you want to axis 0 then the stack row wise
print(result)
# Output:
# [[1 4]
#  [2 5]
#  [3 6]]


[[1 4]
 [2 5]
 [3 6]]


# np.vstack() – Stack arrays vertically (row-wise)

In [79]:
result = np.vstack((a, b))
print(result)
# Output:
# [[1 2 3]
#  [4 5 6]]


[[1 2 3]
 [4 5 6]]


# np.hstack() – Stack arrays horizontally (column-wise)

In [80]:
result = np.hstack((a, b))
print(result)
# Output:
# [1 2 3 4 5 6]


[1 2 3 4 5 6]


# np.dstack() – Stack arrays depth-wise (along third axis)

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = np.dstack((a, b))
print(result)
# Output:
# [[[1 4]
#   [2 5]
#   [3 6]]]


# Splitting Array in Numpy

In [87]:
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6])
result = np.split(a, 3)  # Split into 3 equal parts

print(result)
# Output: [array([1, 2]), array([3, 4]), array([5, 6])]


[array([1, 2]), array([3, 4]), array([5, 6])]


In [89]:
a = np.array([1, 2, 3, 4, 5])
result = np.array_split(a, 3)

print(result)
# Output: [array([1, 2]), array([3, 4]), array([5])]
# unequal part

[array([1, 2]), array([3, 4]), array([5])]


# np.hsplit() – Split horizontally (columns)

In [98]:
a = np.array([[1, 2, 3], [4, 5, 6]])
result = np.hsplit(a, 1)

print(result)
# Output: [array([[1], [4]]), array([[2], [5]]), array([[3], [6]])]


[array([[1, 2, 3],
       [4, 5, 6]])]


# np.vsplit() – Split vertically (rows)

In [102]:
a = np.array([[1, 2, 3], [4, 5, 6]])
result = np.vsplit(a, 2)

print(result)
# Output: [array([[1, 2, 3]]), array([[4, 5, 6]])]


[array([[1, 2, 3]]), array([[4, 5, 6]])]


# ✅ np.dsplit() – Split depth-wise (for 3D arrays)

In [103]:
a = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
result = np.dsplit(a, 2)

print(result)
# Output: 2 arrays split along depth (3rd axis)


[array([[[1],
        [3]],

       [[5],
        [7]]]), array([[[2],
        [4]],

       [[6],
        [8]]])]


# CHAPTER - 5
# Broadcasting & Vectorization

✅ 1. Vectorization
Definition:
Vectorization is the process of replacing explicit loops with array expressions to perform operations more efficiently.

Instead of looping over elements, NumPy does operations on whole arrays using optimized C code under the hood.

In [105]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Vectorized addition (no loops needed)
result = a + b
print(result)  # Output: [5 7 9]


[5 7 9]


✅ 2. Broadcasting
Definition:
Broadcasting is a powerful feature that allows NumPy to perform operations on arrays of different shapes as long as certain rules are followed.

It automatically stretches or duplicates the smaller array to match the shape of the larger one.



In [106]:
a = np.array([1, 2, 3])
b = 5

result = a + b
print(result)  # Output: [6 7 8]


[6 7 8]


# Example using loop Boradcasting 


In [126]:
product = [100, 45, 56, 67]
discount = 10
price_d = []

for pro in product:
    prices = pro - (pro * discount / 100)
    price_d.append(prices)

print(price_d)


[90.0, 40.5, 50.4, 60.3]


In [133]:
# Using Numpy array
product = [100, 45, 56, 67]

arr =np.array(product)
discount = 10
F_prices = arr - (arr * discount/100)
print(F_prices)

[90.  40.5 50.4 60.3]


In [138]:
product = [100, 45, 56, 67]
product1 = [100, 45, 56, ]
arr = np.array(product)
arr1 = np.array(product1)
print(arr)
print(arr1)
print(arr + arr1)

[100  45  56  67]
[100  45  56]


ValueError: operands could not be broadcast together with shapes (4,) (3,) 

 # Vectorization

In [140]:
# loop aproach using list
list1 = [23,45,4,5]
list2 = [23,45,4,5]

result = [x+y for x,y in zip(list1,list2)]
print(result)



[46, 90, 8, 10]


In [141]:
# fast vectorization approach 

In [143]:
product = [100, 45, 56, 67]
product1 = [100, 45, 56,34 ]
arr = np.array(product)
arr1 = np.array(product1)
# print(arr)
# print(arr1)
print(arr + arr1)

[200  90 112 101]


In [144]:
# Boradcasting : it expand the small array to large -- fast than loop ---  
# vectrization : operation easily entire array -- 


# CHAPTER - 6
# Handling Missing & Special Values

In [147]:
# isnan()

In [145]:
import numpy as np

data = np.array([1, 2, np.nan, 4, 5,np.nan])

# Check where values are NaN
np.isnan(data)


array([False, False,  True, False, False,  True])

In [ ]:
# nan_to_num 
# this function is use for fill the value of any nan array 

In [151]:
import numpy as np

data = np.array([1, 2, np.nan, 4, 5,np.nan])

# Check where values are NaN
np.isnan(data)
# Replace NaN with a specific value, e.g., 0
data_filled = np.nan_to_num(data, nan=0000)
data_filled


array([1., 2., 0., 4., 5., 0.])

In [154]:
import numpy as np

data = np.array([1, 2, np.nan, 4, 5,np.nan])

# Check where values are NaN
# np.isnan(data)

clean_data = data[~np.isnan(data)]
clean_data


array([1., 2., 4., 5.])

In [165]:
data = np.array([1, 2, np.inf, -np.inf, 5])

np.isinf(data)         # True for both +inf and -inf

# replace the infinit 
arr = np.nan_to_num(data,posinf=100,neginf = -100)
arr

array([   1.,    2.,  100., -100.,    5.])

# Capstone Projects

In [184]:
import pandas as pd 
import numpy as np
df = pd.read_csv('employees.csv')
# df
df.head()


EMPLOYEE_ID FIRST_NAME  LAST_NAME     EMAIL  PHONE_NUMBER  HIRE_DATE  \
0          198     Donald   OConnell  DOCONNEL  650.507.9833  21-JUN-07   
1          199    Douglas      Grant    DGRANT  650.507.9844  13-JAN-08   
2          200   Jennifer     Whalen   JWHALEN  515.123.4444  17-SEP-03   
3          201    Michael  Hartstein  MHARTSTE  515.123.5555  17-FEB-04   
4          202        Pat        Fay      PFAY  603.123.6666  17-AUG-05   

     JOB_ID  SALARY COMMISSION_PCT MANAGER_ID  DEPARTMENT_ID  
0  SH_CLERK    2600             -         124             50  
1  SH_CLERK    2600             -         124             50  
2   AD_ASST    4400             -         101             10  
3    MK_MAN   13000             -         100             20  
4    MK_REP    6000             -         201             20

# Checking the Missing value 

In [187]:

print("missing value in each column")
# print(df.isnull())
print(df.isnull().sum())


missing value in each column
EMPLOYEE_ID       0
FIRST_NAME        0
LAST_NAME         0
EMAIL             0
PHONE_NUMBER      0
HIRE_DATE         0
JOB_ID            0
SALARY            0
COMMISSION_PCT    0
MANAGER_ID        0
DEPARTMENT_ID     0
dtype: int64


# Drop single not useable column

In [191]:
# df.drop('column_name', axis=1, inplace=False)
df.drop('COMMISSION_PCT', axis=1, inplace=True)
# df.head(4)

In [192]:
df.head(2)

EMPLOYEE_ID FIRST_NAME LAST_NAME     EMAIL  PHONE_NUMBER  HIRE_DATE  \
0          198     Donald  OConnell  DOCONNEL  650.507.9833  21-JUN-07   
1          199    Douglas     Grant    DGRANT  650.507.9844  13-JAN-08   

     JOB_ID  SALARY MANAGER_ID  DEPARTMENT_ID  
0  SH_CLERK    2600        124             50  
1  SH_CLERK    2600        124             50

In [194]:
df['Avg Salary'] = None

In [202]:
df['Avg Salary'].fillna(df['SALARY'].mean(), inplace=True)
# df


In [204]:
df.replace(np.inf,-np.inf,np.nan,inplace = True)
df.fillna(df.mean(),inplace =True)

TypeError: NDFrame.replace() takes from 1 to 3 positional arguments but 4 positional arguments (and 1 keyword-only argument) were given

In [206]:
df.drop_duplicates(inplace=True)
# df

EMPLOYEE_ID   FIRST_NAME    LAST_NAME     EMAIL  PHONE_NUMBER  HIRE_DATE  \
0           198       Donald     OConnell  DOCONNEL  650.507.9833  21-JUN-07   
1           199      Douglas        Grant    DGRANT  650.507.9844  13-JAN-08   
2           200     Jennifer       Whalen   JWHALEN  515.123.4444  17-SEP-03   
3           201      Michael    Hartstein  MHARTSTE  515.123.5555  17-FEB-04   
4           202          Pat          Fay      PFAY  603.123.6666  17-AUG-05   
5           203        Susan       Mavris   SMAVRIS  515.123.7777  07-JUN-02   
6           204      Hermann         Baer     HBAER  515.123.8888  07-JUN-02   
7           205      Shelley      Higgins  SHIGGINS  515.123.8080  07-JUN-02   
8           206      William        Gietz    WGIETZ  515.123.8181  07-JUN-02   
9           100       Steven         King     SKING  515.123.4567  17-JUN-03   
10          101        Neena      Kochhar  NKOCHHAR  515.123.4568  21-SEP-05   
11          102          Lex      De Haan   LDEHAAN  515.123.4569  13-JAN-01   
12          103    Alexander       Hunold   AHUNOLD  590.423.4567  03-JAN-06   
13          104        Bruce        Ernst    BERNST  590.423.4568  21-MAY-07   
14          105        David       Austin   DAUSTIN  590.423.4569  25-JUN-05   
15          106        Valli    Pataballa  VPATABAL  590.423.4560  05-FEB-06   
16          107        Diana      Lorentz  DLORENTZ  590.423.5567  07-FEB-07   
17          108        Nancy    Greenberg  NGREENBE  515.124.4569  17-AUG-02   
18          109       Daniel       Faviet   DFAVIET  515.124.4169  16-AUG-02   
19          110         John         Chen     JCHEN  515.124.4269  28-SEP-05   
20          111       Ismael      Sciarra  ISCIARRA  515.124.4369  30-SEP-05   
21          112  Jose Manuel        Urman   JMURMAN  515.124.4469  07-MAR-06   
22          113         Luis         Popp     LPOPP  515.124.4567  07-DEC-07   
23          114          Den     Raphaely  DRAPHEAL  515.127.4561  07-DEC-02   
24          115    Alexander         Khoo     AKHOO  515.127.4562  18-MAY-03   
25          116       Shelli        Baida    SBAIDA  515.127.4563  24-DEC-05   
26          117        Sigal       Tobias   STOBIAS  515.127.4564  24-JUL-05   
27          118          Guy       Himuro   GHIMURO  515.127.4565  15-NOV-06   
28          119        Karen   Colmenares  KCOLMENA  515.127.4566  10-AUG-07   
29          120      Matthew        Weiss    MWEISS  650.123.1234  18-JUL-04   
30          121         Adam        Fripp    AFRIPP  650.123.2234  10-APR-05   
31          122        Payam     Kaufling  PKAUFLIN  650.123.3234  01-MAY-03   
32          123       Shanta      Vollman  SVOLLMAN  650.123.4234  10-OCT-05   
33          124        Kevin      Mourgos  KMOURGOS  650.123.5234  16-NOV-07   
34          125        Julia        Nayer    JNAYER  650.124.1214  16-JUL-05   
35          126        Irene  Mikkilineni  IMIKKILI  650.124.1224  28-SEP-06   
36          127        James       Landry   JLANDRY  650.124.1334  14-JAN-07   
37          128       Steven       Markle   SMARKLE  650.124.1434  08-MAR-08   
38          129        Laura       Bissot   LBISSOT  650.124.5234  20-AUG-05   
39          130        Mozhe     Atkinson  MATKINSO  650.124.6234  30-OCT-05   
40          131        James       Marlow   JAMRLOW  650.124.7234  16-FEB-05   
41          132           TJ        Olson   TJOLSON  650.124.8234  10-APR-07   
42          133        Jason       Mallin   JMALLIN  650.127.1934  14-JUN-04   
43          134      Michael       Rogers   MROGERS  650.127.1834  26-AUG-06   
44          135           Ki          Gee      KGEE  650.127.1734  12-DEC-07   
45          136        Hazel   Philtanker  HPHILTAN  650.127.1634  06-FEB-08   
46          137       Renske       Ladwig   RLADWIG  650.121.1234  14-JUL-03   
47          138      Stephen       Stiles   SSTILES  650.121.2034  26-OCT-05   
48          139         John          Seo      JSEO  650.121.2019  12-FEB-06   
49  

In [213]:
# df.drop(8, inplace=True)
df

EMPLOYEE_ID   FIRST_NAME    LAST_NAME     EMAIL  PHONE_NUMBER  HIRE_DATE  \
0           198       Donald     OConnell  DOCONNEL  650.507.9833  21-JUN-07   
1           199      Douglas        Grant    DGRANT  650.507.9844  13-JAN-08   
2           200     Jennifer       Whalen   JWHALEN  515.123.4444  17-SEP-03   
3           201      Michael    Hartstein  MHARTSTE  515.123.5555  17-FEB-04   
4           202          Pat          Fay      PFAY  603.123.6666  17-AUG-05   
5           203        Susan       Mavris   SMAVRIS  515.123.7777  07-JUN-02   
6           204      Hermann         Baer     HBAER  515.123.8888  07-JUN-02   
7           205      Shelley      Higgins  SHIGGINS  515.123.8080  07-JUN-02   
9           100       Steven         King     SKING  515.123.4567  17-JUN-03   
10          101        Neena      Kochhar  NKOCHHAR  515.123.4568  21-SEP-05   
11          102          Lex      De Haan   LDEHAAN  515.123.4569  13-JAN-01   
12          103    Alexander       Hunold   AHUNOLD  590.423.4567  03-JAN-06   
13          104        Bruce        Ernst    BERNST  590.423.4568  21-MAY-07   
14          105        David       Austin   DAUSTIN  590.423.4569  25-JUN-05   
15          106        Valli    Pataballa  VPATABAL  590.423.4560  05-FEB-06   
16          107        Diana      Lorentz  DLORENTZ  590.423.5567  07-FEB-07   
17          108        Nancy    Greenberg  NGREENBE  515.124.4569  17-AUG-02   
18          109       Daniel       Faviet   DFAVIET  515.124.4169  16-AUG-02   
19          110         John         Chen     JCHEN  515.124.4269  28-SEP-05   
20          111       Ismael      Sciarra  ISCIARRA  515.124.4369  30-SEP-05   
21          112  Jose Manuel        Urman   JMURMAN  515.124.4469  07-MAR-06   
22          113         Luis         Popp     LPOPP  515.124.4567  07-DEC-07   
23          114          Den     Raphaely  DRAPHEAL  515.127.4561  07-DEC-02   
24          115    Alexander         Khoo     AKHOO  515.127.4562  18-MAY-03   
25          116       Shelli        Baida    SBAIDA  515.127.4563  24-DEC-05   
26          117        Sigal       Tobias   STOBIAS  515.127.4564  24-JUL-05   
27          118          Guy       Himuro   GHIMURO  515.127.4565  15-NOV-06   
28          119        Karen   Colmenares  KCOLMENA  515.127.4566  10-AUG-07   
29          120      Matthew        Weiss    MWEISS  650.123.1234  18-JUL-04   
30          121         Adam        Fripp    AFRIPP  650.123.2234  10-APR-05   
31          122        Payam     Kaufling  PKAUFLIN  650.123.3234  01-MAY-03   
32          123       Shanta      Vollman  SVOLLMAN  650.123.4234  10-OCT-05   
33          124        Kevin      Mourgos  KMOURGOS  650.123.5234  16-NOV-07   
34          125        Julia        Nayer    JNAYER  650.124.1214  16-JUL-05   
35          126        Irene  Mikkilineni  IMIKKILI  650.124.1224  28-SEP-06   
36          127        James       Landry   JLANDRY  650.124.1334  14-JAN-07   
37          128       Steven       Markle   SMARKLE  650.124.1434  08-MAR-08   
38          129        Laura       Bissot   LBISSOT  650.124.5234  20-AUG-05   
39          130        Mozhe     Atkinson  MATKINSO  650.124.6234  30-OCT-05   
40          131        James       Marlow   JAMRLOW  650.124.7234  16-FEB-05   
41          132           TJ        Olson   TJOLSON  650.124.8234  10-APR-07   
42          133        Jason       Mallin   JMALLIN  650.127.1934  14-JUN-04   
43          134      Michael       Rogers   MROGERS  650.127.1834  26-AUG-06   
44          135           Ki          Gee      KGEE  650.127.1734  12-DEC-07   
45          136        Hazel   Philtanker  HPHILTAN  650.127.1634  06-FEB-08   
46          137       Renske       Ladwig   RLADWIG  650.121.1234  14-JUL-03   
47          138      Stephen       Stiles   SSTILES  650.121.2034  26-OCT-05   
48          139         John          Seo      JSEO  650.121.2019  12-FEB-06   
49          140       Joshua        Patel    JPATEL  650.121.1834  06-APR-06   

   

In [214]:
df.to_csv("clean file .csv")